version: '3.8'

services:
  # MySQL Database
  db:
    image: postgres:15
    container_name: solar_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
      POSTGRES_DATABASE: ${DB_NAME:-new_solar}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solar_network

  # Flask Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-123456789}
      DB_NAME: ${DB_NAME:-new_solar}
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY:-change-this-secret-key-in-production}
      FLASK_DEBUG: "false"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - solar_network
    volumes:
      - ./data.sql:/app/data.sql:ro

volumes:
  postgres_data:
    driver: local

networks:
  solar_network:
    driver: bridge