version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: solar_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456789}
      MYSQL_DATABASE: ${DB_NAME:-new_solar}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-123456789}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solar_network

  # Flask Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-123456789}
      DB_NAME: ${DB_NAME:-new_solar}
      DB_PORT: 3306
      SECRET_KEY: ${SECRET_KEY:-change-this-secret-key-in-production}
      FLASK_DEBUG: "false"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - solar_network
    volumes:
      - ./data.sql:/app/data.sql:ro

volumes:
  mysql_data:
    driver: local

networks:
  solar_network:
    driver: bridge

