name: Deploy to AWS EC2

on:
  push:
    branches: [main, lab4]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 98.88.76.225
          username: admin
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/admin/database_labs

            # Switch to the branch that triggered the workflow
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            # Navigate to app directory
            cd mybd

            # Stop existing containers
            sudo docker-compose down || true

            # Build new Docker image
            sudo docker-compose build --no-cache

            # Start new containers
            sudo docker-compose up -d

            # Wait for containers to start
            sleep 30

            # Check if container is running
            if sudo docker-compose ps | grep solar_app; then
              echo "✅ Container deployed successfully"
            else
              echo "❌ Container failed to start"
              exit 1
            fi

            echo "🚀 Deployment completed at $(date)"

      - name: Health Check
        run: |
          sleep 10
          response=$(curl -s -o /dev/null -w "%{http_code}" http://98.88.76.225:5000/)
          if [ $response -eq 200 ]; then
            echo "✅ Application is running successfully!"
            echo "🌐 Main page: http://98.88.76.225:5000/"
            echo "📚 Swagger UI: http://98.88.76.225:5000/swagger/"
          else
            echo "❌ Health check failed with status code: $response"
            exit 1
          fi

      - name: Notify on success
        if: success()
        run: echo "✅ Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "❌ Deployment failed!"
